FROM golang:1.17-bullseye AS builder

WORKDIR /src/
COPY . .

RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bullseye

EXPOSE 3000

WORKDIR /app/
COPY --from=builder /app/webapi ./

CMD ["/app/webapi"]
